### ISSUE TITLE
tweed:request_sync failure

### ISSUE THREAD

**Issue by Luxley** [Siphalor/tweed-api#2]
Heya! Getting a packet failure!
This is for a 1.14 server that im running
I was told to report over here from: https://github.com/CottonMC/SkillCheck/issues/18

[latest.log](https://github.com/Siphalor/tweed-api/files/3205626/latest.log)

**Comment by Siphalor** [comment]
Should be fixed now ;)

**Comment by Luxley** [comment]
@Siphalor i know you said its fixed now but how would i fix it on my end?

**Comment by Siphalor** [comment]
I see you are using Spice of Fabric. 
Due to my other projects sof is sadly stuck in an ugly beta. 
I could release another one with the tweed issue fixed but SoF is a bit rough at the current development state. 
There might come a little larger SoF release soon™ but I can't guarantee for it now. 
I'll reply if the next SoF release fixing this annoying bug is out.

**Comment by Siphalor** [comment]
Hopefully works with the latest beta of Spice of Fabric :)
