### ISSUE TITLE
Mod did not save Config changes 

### ISSUE THREAD

**Issue by Luxley** [Siphalor/tweed-api#3]
Hi siphalor.

I tried changing values in the config through clientside Mod Menu. Saved the values and then closed the game to transfer the mod .jar and config to server. 

None of the changes where retained, both client and server.

**Comment by Siphalor** [comment]
Okay, I'm going to investigate that again.

**Comment by Fourmisain** [comment]
Currently debugging and trying to understand how tweed works, alongside mouse-wheelie and ModMenu.

I see that at this point a ConfigFile with the modname mousewheelie is created
https://github.com/Siphalor/tweed-api/blob/78ad936455ca086ec3f1ab59ea40e6ef1f7be707/src/main/java/de/siphalor/tweed/config/POJOConverter.java#L56
What I don't understand is what happens immediately after it,

https://github.com/Siphalor/tweed-api/blob/78ad936455ca086ec3f1ab59ea40e6ef1f7be707/src/main/java/de/siphalor/tweed/config/POJOConverter.java#L58

On the first glance this looks like it wants to scan mousewheelie's [MWConfig](https://github.com/Siphalor/mouse-wheelie/blob/9d695b2f9e5ef0aa30910eab35c3a3ba06642360/src/main/java/de/siphalor/mousewheelie/MWConfig.java#L19) for the `@AConfigFixer` annotated `fixConfig`.
But `configFile.getClass()` is just `ConfigFile.class`, so it instead scans the methods of tweed's [ConfigFile](https://github.com/Siphalor/tweed-api/blob/v3-1.16/src/main/java/de/siphalor/tweed/config/ConfigFile.java), which of course doesn't have any such annotationed methods - this would explain why I couldn't get `fixConfig` to work.

Apart from that, I still have no idea where the button presses in ModMenu cause a change in `configFile` - I'm assuming that's how it would work.
The action of ModMenu's "Save & Quit" button is set here
https://github.com/Siphalor/tweed-api/blob/ddd993029fb578c5b3e8f145338129e710aa9c47/src/main/java/de/siphalor/tweed/tailor/ClothTailor.java#L97
But after changing some settings and pressing "Save & Quit", [`save`](https://github.com/Siphalor/tweed-api/blob/ddd993029fb578c5b3e8f145338129e710aa9c47/src/main/java/de/siphalor/tweed/tailor/ClothTailor.java#L158)'s `configFile` parameter seems to be empty, which I verified via this hacky output:
```
try (StringWriter w = new StringWriter()) {
	((DataObject<JsonValue>)configFile.getDataSerializer().newObject()).getRaw().writeTo(w);
	System.out.println(w.getBuffer()); // --> "{}"
} catch (IOException e) {e.printStackTrace();}
```

And now I'm not sure where exactly to go.
There have to be some button events for the generated setting buttons somewhere, right?
From what I see ingame, mousewheelie's settings aren't not just not saved, but they not even register.
For example, disabling item scrolling from ModMenu, doesn't disable the feature ingame, changing the config file manually works however.

**Comment by Siphalor** [comment]
> I see that at this point a ConfigFile with the modname mousewheelie is created

yep

> On the first glance this looks like it wants to scan mousewheelie's MWConfig for the @AConfigFixer annotated fixConfig.
But configFile.getClass() is just ConfigFile.class, so it instead scans the methods of tweed's ConfigFile, which of course doesn't have any such annotationed methods - this would explain why I couldn't get fixConfig to work.

You're totally right about that. I could swear I had this look at the pojo once but it was broken :/ I'm gonna quickly fix that.

> Apart from that, I still have no idea where the button presses in ModMenu cause a change in configFile - I'm assuming that's how it would work.

To begin the config screen is not actually displayed by ModMenu. ModMenu just handles the config button and then hands it over to Tweed in this case which builds the config screen with ClothConfig and then hands the control over to that.

> But after changing some settings and pressing "Save & Quit", save's configFile parameter seems to be empty, which I verified via this hacky output:

That is really strange - I'm gonna look at that

> From what I see ingame, mousewheelie's settings aren't not just not saved, but they not even register.
> For example, disabling item scrolling from ModMenu, doesn't disable the feature ingame, changing the config file manually works however.

That is the most annoying part of this issue. I'm completely unable to reproduce it. For me saving ingame works just fine. The biggest issues I experienced were on a server but also only occasionally and I couldn't pin it down on anything :/

*Thanks for looking into this issue. You've already been a great help and I'm gonna see if I can find the root cause of this bug because of the new clues 😃*

**Comment by Siphalor** [comment]
Let's see if that fix actually does what it promises in production

**Comment by Fourmisain** [comment]
I can confirm this is now fixed!
