### ISSUE TITLE
Cancel button reopens Tweed settings

### ISSUE THREAD

**Issue by Madis0** [Siphalor/tweed-api#8]
When opening the Tweed settings via Mod Menu config button, it is nearly impossible to exit the Tweed screen, as it keeps reopening the Tweed settings. I once managed to exit it by holding Esc...

- Minecraft 1.16.1
- Fabric API 0.13.1 build 370
- Fabric Loader 0.8.8 build 202
- Tweed 3.0.0 beta 9 probably bundled by Mouse Tweaks

**Comment by Siphalor** [comment]
Ok, I've been collecting some context:
This happens with Tweed's ModMenu entry **only when a world is open**.

When the user clicks to select the entry in ModMenu the config opens instantly and cannot be closed easily.

I don't know why this happens but I would suspect that this happens because I provide both the screen as direct mod screen but also through the library-provider. As such I would claim that this is a fault on ModMenu's end. As such I'm gonna open an issue there too :)

PS: it's called Mouse Wheelie ^^

**Comment by oOBoomberOo** [comment]
I have the same issue and I also notice that instead of re-opening the config screen there's actually multiple config screen open at the same time (50+) and it seems to increase each time it happens.

EDIT: Siphalor corrected me

**Comment by Siphalor** [comment]
> I have the same issue and I also notice that instead of re-opening the config screen there's actually multiple config screen open at the same time (50+) and it seems to increase each time it happens.

That's actually not the case. Like I described at the ModMenu issue, it happens because Tweed immediately syncs and reopens the screen when ModMenu tries to render the mod overview.

There is only one screen open at a time. 

Escaping the loop is only possible if it happens that your key press is sent before to the active screen before it actually had time to render. This is obviously very unlikely to happen.
